SITE = {
    "brand": "The New City Furniture Company Limited",
    "tagline": "Quality furniture at rock-bottom prices.",
    "summary": (
        "A Jamaican-owned furniture manufacturer and retailer offering real wood "
        "furniture, Pure Comfort bedding, living room suites, bedroom storage, "
        "delivery support, and friendly showroom guidance."
    ),
    "phone": "+1 876 948 5654",
    "branchPhone": "+1 876 918 0251",
    "whatsappUrl": "https://wa.me/18769485654",
    "email": "thenewcityfurniture@gmail.com",
    "website": "https://www.thenewcityfurnitureja.com",
    "currency": "JMD",
    "address": "20 Orange Street, Kingston, Jamaica",
    "showroom": "20 Orange Street, Kingston, Jamaica",
    "branchAddress": "Shop 3, Hendon Mall, Savanna-la-Mar, Westmoreland",
    "hours": "Mon-Tue 9:00 AM-6:00 PM, Wed 9:00 AM-3:00 PM, Thu-Sat 9:00 AM-6:00 PM, Sun Closed",
    "founded": "Established in Jamaica around 1999-2000",
    "facebookUrl": "https://www.facebook.com/650028818388032",
    "instagramUrl": "",
    "deliveryLabel": "Delivery available in Jamaica; final cost confirmed by area",
    "businessDescription": (
        "Known for locally made furniture, native wood pieces, Pure Comfort "
        "mattresses, living room suites, bedroom furniture, wardrobes, dressers, "
        "bed bases, headboards, bar stools, and lounge chairs."
    ),
    "paymentPlanNote": "Custom payment plans and cash discounts are promoted in public business listings.",
    "paymentNote": (
        "Checkout is ready to connect to Jamaican-friendly payment options such "
        "as WiPay, Fygaro, NCB e-commerce, Lynk, or card payment links once the "
        "merchant account is confirmed."
    ),
    "sourceNote": "Public details checked from JMEA, FindYello, TodosBiz, WorldPlaces, and FiwiBusiness listings.",
}

CATEGORIES = [
    {
        "slug": "living-room",
        "title": "Living Room",
        "text": "Sofas, sectionals, accent chairs, coffee tables, and media storage.",
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "slug": "bedroom",
        "title": "Bedroom",
        "text": "Beds, dressers, nightstands, wardrobes, and complete bedroom sets.",
        "image": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "slug": "dining",
        "title": "Dining",
        "text": "Dining tables, chairs, benches, hutches, and hosting-ready sets.",
        "image": "https://images.unsplash.com/photo-1617098474202-0d0d7f60c56b?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "slug": "mattresses",
        "title": "Mattresses",
        "text": "Pure Comfort bedding, mattress sizes, bases, and sleep accessories.",
        "image": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "slug": "home-office",
        "title": "Home Office",
        "text": "Desks, task seating, shelving, and storage for focused rooms.",
        "image": "https://images.unsplash.com/photo-1593476550610-87baa860004a?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "slug": "custom-furniture",
        "title": "Custom Furniture",
        "text": "Locally made wood furniture shaped around your space and finish.",
        "image": "https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?auto=format&fit=crop&w=1200&q=82",
    },
]

PRODUCTS = [
    {
        "sku": "NC-LR-001",
        "slug": "solid-wood-sofa-set",
        "name": "Solid Wood Sofa Set",
        "category": "living-room",
        "categoryLabel": "Living Room",
        "price": 245000,
        "compareAt": 268000,
        "badge": "Real wood",
        "stock": 4,
        "leadTime": "Ready in 3-5 days",
        "material": "Local hardwood frame",
        "finish": "Warm walnut",
        "dimensions": "84 in W x 34 in D",
        "description": "A durable living-room anchor with deep cushions, real wood character, and a premium showroom presence.",
        "features": ["Solid frame", "Performance fabric option", "Matching chair available"],
        "image": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-BR-104",
        "slug": "storage-bed-frame",
        "name": "Storage Bed Frame",
        "category": "bedroom",
        "categoryLabel": "Bedroom",
        "price": 138000,
        "compareAt": 152000,
        "badge": "Locally made",
        "stock": 2,
        "leadTime": "Made to order",
        "material": "Hardwood and veneer",
        "finish": "Natural oak",
        "dimensions": "Queen or king",
        "description": "A clean bedroom centerpiece with practical storage and a crafted wood finish.",
        "features": ["Under-bed drawers", "Queen and king sizing", "Custom stain option"],
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-DN-052",
        "slug": "family-dining-set",
        "name": "Family Dining Set",
        "category": "dining",
        "categoryLabel": "Dining",
        "price": 186000,
        "compareAt": 0,
        "badge": "Durable finish",
        "stock": 6,
        "leadTime": "Ready in 1 week",
        "material": "Solid and engineered wood",
        "finish": "Satin espresso",
        "dimensions": "6-seat set",
        "description": "A hosting-ready dining set sized for family meals, holidays, and everyday use.",
        "features": ["Six chairs included", "Heat-resistant finish", "Bench option"],
        "image": "https://images.unsplash.com/photo-1617103996702-96ff29b1c467?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-MT-210",
        "slug": "pure-comfort-mattress",
        "name": "Pure Comfort Mattress",
        "category": "mattresses",
        "categoryLabel": "Bedding",
        "price": 72000,
        "compareAt": 82000,
        "badge": "Pure Comfort",
        "stock": 12,
        "leadTime": "Same-week delivery",
        "material": "Pocket spring and comfort foam",
        "finish": "Medium firm",
        "dimensions": "Twin, full, queen, king",
        "description": "Supportive bedding for cooler, more comfortable rest with clear size options.",
        "features": ["Multiple sizes", "Medium-firm support", "Base pairing available"],
        "image": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-PC-001",
        "slug": "pure-comfort-good-sleep-mattress",
        "name": "Pure Comfort Good Sleep Mattress",
        "category": "mattresses",
        "categoryLabel": "Bedding",
        "price": 0,
        "compareAt": 0,
        "badge": "Pure Comfort",
        "stock": 0,
        "leadTime": "Call for availability",
        "material": "Locally made mattress",
        "finish": "Twin, double, queen",
        "dimensions": "Twin, double, queen",
        "description": "Pure Comfort Good Sleep mattress line, listed for twin, double, and queen sizes.",
        "features": ["Locally made", "Multiple sizes", "Ask showroom for current price"],
        "image": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-PC-002",
        "slug": "pure-comfort-city-sleeper-mattress",
        "name": "Pure Comfort City Sleeper Mattress",
        "category": "mattresses",
        "categoryLabel": "Bedding",
        "price": 0,
        "compareAt": 0,
        "badge": "Pure Comfort",
        "stock": 0,
        "leadTime": "Call for availability",
        "material": "Locally made mattress",
        "finish": "Double, queen",
        "dimensions": "Double, queen",
        "description": "Pure Comfort City Sleeper mattress line, listed for double and queen sizes.",
        "features": ["Locally made", "Double and queen sizes", "Ask showroom for current price"],
        "image": "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-HO-033",
        "slug": "executive-writing-desk",
        "name": "Executive Writing Desk",
        "category": "home-office",
        "categoryLabel": "Home Office",
        "price": 92000,
        "compareAt": 0,
        "badge": "New arrival",
        "stock": 3,
        "leadTime": "Ready in 3-5 days",
        "material": "Hardwood top",
        "finish": "Matte teak",
        "dimensions": "60 in W x 28 in D",
        "description": "A restrained desk with storage, cable access, and a finish that suits modern home offices.",
        "features": ["Cable pass-through", "Two drawers", "Matching shelf available"],
        "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=82",
    },
    {
        "sku": "NC-CF-009",
        "slug": "custom-wardrobe-system",
        "name": "Custom Wardrobe System",
        "category": "custom-furniture",
        "categoryLabel": "Custom",
        "price": 310000,
        "compareAt": 0,
        "badge": "Consultation",
        "stock": 0,
        "leadTime": "Quote required",
        "material": "Custom wood build",
        "finish": "Client selected",
        "dimensions": "Measured to fit",
        "description": "A fitted wardrobe concept for customers who need a measured storage solution.",
        "features": ["Measured design", "Finish samples", "Hardware options"],
        "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=82",
    },
]

TRUST_ITEMS = [
    "Locally made options",
    "Real wood construction",
    "Delivery coordination",
    "Secure checkout ready",
]

PROOF_POINTS = [
    {
        "title": "Designed for confident browsing",
        "text": "Visitors can search, filter, compare details, and move from discovery to WhatsApp or cart without friction.",
    },
    {
        "title": "Built for Jamaican commerce",
        "text": "Checkout captures delivery and payment intent while staying ready for local payment provider integration.",
    },
    {
        "title": "Admin operations foundation",
        "text": "Inventory, product visibility, order review, and content settings have protected API routes and an admin UI.",
    },
]

ORDERS = [
    {
        "id": "NC-1007",
        "customer": "Marsha Campbell",
        "status": "Awaiting payment link",
        "total": 317000,
        "method": "WhatsApp quote",
        "created": "2026-08-15",
        "items": ["Solid Wood Sofa Set", "Pure Comfort Mattress"],
    },
    {
        "id": "NC-1008",
        "customer": "Andre Williams",
        "status": "Delivery scheduled",
        "total": 186000,
        "method": "Card readiness",
        "created": "2026-08-16",
        "items": ["Family Dining Set"],
    },
]

CONTENT_BLOCKS = [
    {"key": "homepageHero", "status": "Published", "owner": "Marketing", "updated": "2026-08-16"},
    {"key": "deliveryPolicy", "status": "Needs final copy", "owner": "Operations", "updated": "2026-08-14"},
    {"key": "paymentPolicy", "status": "Draft", "owner": "Finance", "updated": "2026-08-12"},
]
